name: Last.fm scrobbler

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with: 
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install required python packages
        run: pip install -r requirements.txt

      - name: Retrieve secrets
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          LASTFM_PASSWORD: ${{ secrets.LASTFM_PASSWORD }}
        run: python scrobble.py

      
